### ISSUE TITLE
Incorporate snowpack

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fissr_explore#6]
We could perhaps add `.elev_percentile_60` to the [rasterstats ](https://pythonhosted.org/rasterstats/manual.html) elevation query in the [makefile](https://github.com/NewGraphEnvironment/fissr_explore/blob/master/scripts/Makefile)?

This relates to poissonconsulting/channel-width-21b#5 .  Not only relevant for channel width but an expansion on habitat (water temp) preferences for species of interest.

**Comment by smnorris** [comment]
Looks reasonable and easy. 
IDs of the source points have changed though so I have to re-run the watershed generation.

**Comment by NewGraphEnvironment** [comment]
Awesomeness
