### ISSUE TITLE
Unpacking arrays or tweaking postgres queries

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fissr_explore#7]
Many of our outputs are exported as csv's with lists (wiithin the same columns) from postgresql using psql2csv .  It may not be trivial to unpack these so we can get summary statistics. 

For now to query for conditions (ex. are there any gradient barriers downstream of the density points that are >20%) seems quite easy 

`library(tidyverse)`  
`library(data.table)` 
`test <- barriers %>%   
  filter(barriers_gradient_dnstr %ilike% '20')`

Going forward to more detailed analysis we can consider the effort required to unpack vs. effort to tweak pg queries to pull out events in wide (ie. one column per type of event) or long format (ie. one row per event) vs just converting from query to geojson so that we can unnest the list columns easily.

**Comment by NewGraphEnvironment** [comment]
Interestingly geojson's such as the [watersheds used for the FISS points](https://github.com/NewGraphEnvironment/fissr_explore/blob/master/R/0150-download-wshds.R) seem to unpack into list columns when imported with `sf::sf_read` which are easily 'unnested' with `tidyr::unnest`.  This may be a more friendly output than csv's not only for this reason but also for compatibility with operating systems other than IOS (pgsql2csv).

**Comment by NewGraphEnvironment** [comment]
spent a bit of time of this and didn't get anywhere.  Thinking we may be better off with geojson for all outputs.  I might be missing something though.  Attempts to unnest the postgres list output columns [here ](https://github.com/NewGraphEnvironment/fissr_explore/blob/master/R/test_unpacking_postgres_output_lists.R)

**Comment by NewGraphEnvironment** [comment]
@smnorris - I now agree with you that geojson is a much better output than csv.  In addition to the issues listed above (ie. unnesting and compatibility) it also seems from my tiny little checks that we may store column types within the geojson which is another massive improvement over the csv format.  Could you put shifting outputs of sql scripts from csv to geojson on your list of "to dos"?

**Comment by smnorris** [comment]
lots of options:
- no shortage of data exchange formats, it doesn't have to be csv/geojson if you prefer something else
- if sticking with csv, I could also dump a sidecar file that defines the types
- geojson for everything is fine as long as working with points, redundant data volume more of an issue with lines/polys
- easy to unpack the arrays before dumping
- could add the data to `features.hillcrestgeo.ca/bcfishobs` rather than dumping to file
- if you have postgres/postgis installed a `pg_dump` output would be super easy for exchange

**Comment by NewGraphEnvironment** [comment]
For most frictionless collaboration at this point I think geojson with the arrays all nicely tucked in (as with the wshed file) should be great.  Unpacking the array columns later may be a good option but I think it might be nice to keep things tight at the start so we can see which of the columns we really want to climb into in the first place.  Unnesting seems easy and as detailed above a data.table::%like% query can give us some quick wins if we only want boolean results to get analysis started. I'll probably eat these words 🦅 .

A sidecar of some sort to define types is smart but lets put that one in our pocket for now due to the gems below.

Adding the data to `features.hillcrestgeo.ca/bcfishobs` rather than dumping to file is next level.  I love it.  Classic Norris. To keep things simple for now can we keep dumping out to geojson in the file and also write in the push to bcfishobs now so we can pull from that location later on in the game if we so please?

`pg_dump` is a step above yet again.  Hmmm... Can we do this one too?  Should it go to a server so that we don't overload the repo?

**Comment by smnorris** [comment]
Ok, geojson for now.
